CREATE TABLE JOBS(
        JOB_ID VARCHAR2(10 BYTE) CONSTRAINT JOB_ID_PK PRIMARY KEY NOT NULL,
        JOB_TITLE VARCHAR2(35 BYTE) NOT NULL,
        MIN_SALARY NUMBER(6),
        MAX_SALARY NUMBER(6)
);

CREATE TABLE EMPLOYEES(
        EMPLOYEE_ID NUMBER(6) CONSTRAINT EMP_EMP_ID_PK PRIMARY KEY NOT NULL,
        FIRST_NAME VARCHAR2(20 BYTE),
        LAST_NAME VARCHAR2(25 BYTE) NOT NULL,
        EMAIL VARCHAR2(25 BYTE) CONSTRAINT EMP_EMAIL_UK UNIQUE NOT NULL,
        PHONE_NUMBER VARCHAR2(25 BYTE),
        HIRE_DATE DATE NOT NULL,
        JOB_ID VARCHAR2(10 BYTE) NOT NULL,
        SALARY NUMBER(8,2),
        COMISSION_PCT NUMBER(2,2),
        MANAGER_ID NUMBER(6),
        DEPARTMENT_ID NUMBER(4)
);

CREATE TABLE EMERGENCY_CONTACTS(
        CONTACT_ID NUMBER CONSTRAINT EMERGENCY_CONTACTS_PK PRIMARY KEY NOT NULL,
        EMPLOYEE_ID NUMBER(6) NOT NULL,
        FIRST_NAME VARCHAR2(100 BYTE) NOT NULL,
        LAST_NAME VARCHAR2(100 BYTE) NOT NULL,
        RELATIONSHIP VARCHAR2(100 BYTE),
        HOME_PHONE VARCHAR2(25 BYTE),
        WORK_PHONE VARCHAR2(25 BYTE),
        CELLPHONE VARCHAR2 (25 BYTE)
);

-- PK COMPOSTA???
CREATE TABLE JOB_HISTORY(
        EMPLOYEE_ID NUMBER(6) NOT NULL,
        START_DATE DATE NOT NULL,
        END_DATE DATE NOT NULL,
        JOB_ID VARCHAR2(10 BYTE) NOT NULL,
        DEPARTMENT_ID NUMBER(4),
        -- IDENTAÇÃO NIVEL DE TABELA
        CONSTRAINT JHIST_EMP_ID_ST_DATE_PK PRIMARY KEY(EMPLOYEE_ID, START_DATE)
);

CREATE TABLE DEPARTMENTS(
        DEPARTMENT_ID NUMBER(4) CONSTRAINT DEPT_ID_PK PRIMARY KEY NOT NULL,
        DEPARTMENT_NAME VARCHAR2(30 BYTE) NOT NULL,
        MANAGER_ID NUMBER(6),
        LOCATION_ID NUMBER(4)
);

CREATE TABLE LOCATIONS(
        LOCATION_ID NUMBER(4) CONSTRAINT LOC_ID_PK PRIMARY KEY NOT NULL,
        STREET_ADDRESS VARCHAR2(40 BYTE),
        POSTAL_CODE VARCHAR2(12 BYTE),
        CITY VARCHAR2(30 BYTE) NOT NULL,
        STATE_PROVINCE VARCHAR2(25 BYTE),
        COUNTRY_ID CHAR(2 BYTE)
);

CREATE TABLE COUNTRIES(
        COUNTRY_ID CHAR(2 BYTE) CONSTRAINT COUNTRY_C_ID_PK PRIMARY KEY NOT NULL,
        COUNTRY_NAME VARCHAR2(40 BYTE),
        REGION_ID NUMBER
);

CREATE TABLE REGIONS(
        REGION_ID NUMBER CONSTRAINT REG_ID_PK PRIMARY KEY NOT NULL,
        REGION_NAME VARCHAR2(25 BYTE)
);

-- FKS
--EMPLOYEES
ALTER TABLE EMPLOYEES
ADD CONSTRAINT EMP_DEPT_FK
FOREIGN KEY(DEPARTMENT_ID)
REFERENCES DEPARTMENTS(DEPARTMENT_ID);

ALTER TABLE EMPLOYEES
ADD CONSTRAINT EMP_JOB_FK
FOREIGN KEY(JOB_ID)
REFERENCES JOBS(JOB_ID);

--TA CERTO ISSO? APARENTEMENTE N
ALTER TABLE EMPLOYEES
ADD CONSTRAINT EMP_MANAGER_FK
FOREIGN KEY(MANAGER_ID)
--JEITO ERRADO
--REFERENCES EMPLOYEES(MANAGER_ID);
--JEITO CERTO
REFERENCES EMPLOYEES;

--EMERGENCY_CONTACTS
ALTER TABLE EMERGENCY_CONTACTS
ADD CONSTRAINT EMP_EMERG_CONT_FK
FOREIGN KEY(EMPLOYEE_ID)
REFERENCES EMPLOYEES(EMPLOYEE_ID);

--JOB HISTORY
ALTER TABLE JOB_HISTORY
ADD CONSTRAINT JHIST_DEPT_FK
FOREIGN KEY(DEPARTMENT_ID)
REFERENCES DEPARTMENTS(DEPARTMENT_ID);

ALTER TABLE JOB_HISTORY
ADD CONSTRAINT JHIST_EMP_FK
FOREIGN KEY(EMPLOYEE_ID)
REFERENCES EMPLOYEES(EMPLOYEE_ID);

ALTER TABLE JOB_HISTORY
ADD CONSTRAINT JHIST_JOB_FK
FOREIGN KEY(JOB_ID)
REFERENCES JOBS(JOB_ID);

--DEPARTMENTS
ALTER TABLE DEPARTMENTS
ADD CONSTRAINT DEPT_LOC_FK
FOREIGN KEY(LOCATION_ID)
REFERENCES LOCATIONS(LOCATION_ID);

ALTER TABLE DEPARTMENTS
ADD CONSTRAINT DEPT_MGR_FK
FOREIGN KEY(MANAGER_ID)
REFERENCES EMPLOYEES;

--LOCATIONS
ALTER TABLE LOCATIONS
ADD CONSTRAINT LOC_C_ID_FK
FOREIGN KEY(COUNTRY_ID)
REFERENCES COUNTRIES(COUNTRY_ID);

--COUNTRIES
ALTER TABLE COUNTRIES
ADD CONSTRAINT COUNTR_REG_FK
FOREIGN KEY(REGION_ID)
REFERENCES REGIONS(REGION_ID);