DROP TABLE JOBS;
DROP TABLE EMPLOYEES;
DROP TABLE EMERGENCY_CONTACTS;
DROP TABLE JOB_HISTORY;
DROP TABLE DEPARTMENTS;
DROP TABLE LOCATIONS;
DROP TABLE COUNTRIES;
DROP TABLE REGIONS;

SHOW RECYCLEBIN;
PURGE RECYCLEBIN;